AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Celosia: CFN Template To Create A DynamoDB Table Encrypted With Customer Managed KMS Key. 

Metadata:
  TemplateName: dynamodb-stack.yaml
  TemplateType: DynamoDB table
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Celosia
  Modification History:
    - 1.0.0  - Oct 20, 2023   -- Initial Version
  Resources: 
    - DynamoDB Table Encrypted With Customer Managed KMS Key
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
        - ProjectName
        - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
        - DynamoDBTableKmsMasterKeyAlias
    #################################### DynamoDB Table ############################################
    - Label: 
        default: 'DynamoDB Configuration'
      Parameters: 
        - DynamoDBTableBaseName
        - DynamoDBTablePartitionKey
        - DynamoDBTablePartitionKeyAttributeType
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## DynamoDB Table ############################################
      DynamoDBTableBaseName: 
        default: 'The Name of the DynamoDB Table.'
      DynamoDBTablePartitionKey:
        default: 'The Name of the Partition Key.'
      DynamoDBTablePartitionKeyAttributeType: 
        default: 'The Datatype of the DynamoDB Partition Key'
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: celosia
    Description: 'The Project Name.'
    Type: String
    MinLength: 5
    MaxLength: 10
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 50, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'  
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String
  ###################################### KMS Key ###################################################
  DynamoDBTableKmsMasterKeyAlias:
    Default: 'SB-KMS'
    Description: 'The KMS Master Key Alias To Be Used For Server Side Encryption.'
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: 'The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash.'
  ###################################### DynamoDB Table ############################################
  DynamoDBTableBaseName:
    Default: product
    Description: 'The Name Of The Dynamodb Table.'
    Type: String
    MinLength: 5
    MaxLength: 15
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: 'The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter.'
  DynamoDBTablePartitionKey:
    Default: partition_id
    Description: 'The Name Of The Dynamodb Partition Key.'
    Type: String
    MinLength: 2
    MaxLength: 30
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-_]*'
    ConstraintDescription: 'Must begin with a letter and contain only alphanumeric characters.'
  DynamoDBTablePartitionKeyAttributeType:
    Default: 'N'
    Description: 'The Datatype Of The Dynamodb Partition Key.'
    Type: String
    AllowedValues: ['N', 'S', 'B']
    ConstraintDescription: 'the Datatype Should Be Either N (number), S (string) Or B (binary)'
Resources:
  ###################################### DynamoDB Table ############################################
  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: !Ref DynamoDBTablePartitionKey
          AttributeType: !Ref DynamoDBTablePartitionKeyAttributeType
      KeySchema: 
        - 
          AttributeName: !Ref DynamoDBTablePartitionKey
          KeyType: 'HASH'
      TableName: !Sub '${ProjectName}-${DynamoDBTableBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      BillingMode: PAY_PER_REQUEST 
      SSESpecification:
            KMSMasterKeyId: !Sub 'alias/${DynamoDBTableKmsMasterKeyAlias}'
            SSEEnabled: True
            SSEType: KMS
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: EnvironmentName
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
Outputs:
  DynamoDBTableArn:
    Description: The Arn of the DynamoDB Table.
    Value: !GetAtt DynamoDBTable.Arn
