AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Celosia: CFN Template to create a SQS Queue Encrypted With Customer Managed KMS Key.

Metadata:
  TemplateName: sqs-stack.yaml
  TemplateType: SQS Queue
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Celosia
  Modification History:
    - 1.0.0  - Oct 20, 2023   -- Initial Version 
  Resources: 
    - SQS Standard Queue Encrypted With Customer Managed KMS Key.
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
        - ProjectName
        - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
        - KmsMasterKeyAlias
    #################################### SQS Queue #################################################
    - Label: 
        default: 'SQS Configuration'
      Parameters: 
        - SQSQueueBaseName
        - DelaySeconds
        - MaximumMessageSize
        - MessageRetentionPeriod
        - ReceiveMessageWaitTimeSeconds
        - VisibilityTimeout
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## KMS Key ###################################################
      KmsMasterKeyAlias:
        default: 'KMS Key Alias.'
      ################################## SQS Queue #################################################
      SQSQueueBaseName:
        default: 'The SQS Queue Name.'
      DelaySeconds:
        default: 'Delay Seconds.'
      MaximumMessageSize:
        default: 'Maximum Message Size.'
      MessageRetentionPeriod: 
        default: 'Message Retention Period.'
      ReceiveMessageWaitTimeSeconds: 
        default: 'Received Message Wait Time Seconds.'
      VisibilityTimeout:
        default: 'Visibility Timeout.'
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: celosia
    Description: 'The Project Name.'
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String
  ###################################### KMS Key ###################################################
  KmsMasterKeyAlias:
    Default: 'SB-KMS'
    Description: 'The KMS Master Key Alias To Be Used For Server Side Encryption.'
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: 'The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash.'
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Type: String
    Description: 'SQS Queue Name.'
  DelaySeconds:
    Type: Number
    Description: 'Delay Seconds.'
    Default: 0
    MinValue: 0
    MaxValue: 900
  MaximumMessageSize:
    Type: Number
    Description: 'Maximum Message Size.'
    Default: 262144
    MinValue: 1024
    MaxValue: 262144
  MessageRetentionPeriod:
    Type: Number
    Description: 'Message Retention Period.'
    Default: 345600
    MinValue: 60
    MaxValue: 1209600
  ReceiveMessageWaitTimeSeconds:
    Type: Number
    Description: 'Received Message Wait Time Seconds.'
    Default: 0
    MinValue: 0
    MaxValue: 20
  VisibilityTimeout:
    Type: Number
    Description: 'Visibility Timeout.'
    Default: 30
    MinValue: 1
    MaxValue: 43200
Resources:
  SQSQueue:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::SQS::Queue
    Properties: 
      DelaySeconds: !Ref DelaySeconds
      KmsMasterKeyId: !Sub 'alias/${KmsMasterKeyAlias}'
      MaximumMessageSize: !Ref MaximumMessageSize
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: !Sub '${ProjectName}-${SQSQueueBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: EnvironmentName
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
      VisibilityTimeout: !Ref VisibilityTimeout
  SQSPolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
       - !Ref SQSQueue
      PolicyDocument: 
        Version: '2012-10-17'
        Id: AllowIncomingAccess
        Statement:
          - Sid: __owner_statement
            Effect: Allow
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - 'SQS:*'
            Resource:
              - !GetAtt SQSQueue.Arn
Outputs:
  SQSQueueURL:
    Description: The URL of the SQS Queue.
    Value: !Ref SQSQueue
  SQSQueueArn:
    Description: The Arn of the SQS Queue.
    Value: !GetAtt SQSQueue.Arn